//! WASM extension loading via wasmtime component model.
//!
//! This module is only compiled when the `wasm-extensions` feature is enabled.
//! It implements [`NativeExtension`] for `.wasm` components that conform to
//! the `crabide:extension@0.1.0` WIT world.
//!
//! # How it works
//!
//! 1. [`WasmExtension::load`] reads the `.wasm` bytes, compiles them with the
//!    shared [`Engine`], sets up a [`Linker`] with all host functions, and
//!    instantiates the component.
//! 2. `NativeExtension` method calls are forwarded to the WASM guest; return
//!    values and side effects (like `status-bar::set-text`) are captured in
//!    [`HostState::pending`] and drained by [`NativeExtension::poll`].
//! 3. WASM traps are caught, logged, and the extension is disabled gracefully.

use std::path::PathBuf;
use std::sync::OnceLock;

// wasmtime 34: all component types live in wasmtime::component::*
// Store is re-exported directly from wasmtime.
use wasmtime::component::{Component, HasSelf, Linker};
use wasmtime::{Config, Engine, Store};

use crate::host::{
    CommandResult, CompletionItem, CompletionKind, ExtensionCategory, ExtensionContext,
    ExtensionDiagnostic, ExtensionManifest, ExtensionOutput, ExtensionSeverity, GutterMarker,
    HoverResult, NativeExtension, TextEdit,
};

// ── WIT bindings ──────────────────────────────────────────────────────────────
//
// `bindgen!` generates:
//   - A `CrabideExtension` struct with typed accessors for each exported interface.
//   - Trait definitions for each host-imported interface (editor::Host, etc.).
//   - `CrabideExtension::add_to_linker` that wires all host functions.
//   - `CrabideExtension::instantiate` that creates an instance.
//
// NOTE: Method names generated by wasmtime::component::bindgen! — these are
// correct for wasmtime 34. If compilation fails with "method not found", check
// the generated bindings in target/debug/build/*/out/ for the actual names.

wasmtime::component::bindgen!({
    world: "crabide-extension",
    path: "../../wit/crabide-extension.wit",
});

// Alias the generated WIT types module for convenience.
// (Must come AFTER bindgen! so the generated `crabide` module exists.)
use crabide::extension::types as wit;

// ── Engine singleton ──────────────────────────────────────────────────────────

static ENGINE: OnceLock<Engine> = OnceLock::new();

fn engine() -> &'static Engine {
    ENGINE.get_or_init(|| {
        let mut cfg = Config::new();
        cfg.wasm_component_model(true);
        Engine::new(&cfg).expect("wasmtime Engine creation failed")
    })
}

// ── Host state ────────────────────────────────────────────────────────────────

/// Per-instance mutable state accessible to all host function implementations.
pub struct HostState {
    // ── Context snapshot (overwritten before each WASM call) ──────────────────
    pub ctx_text: Option<String>,
    pub ctx_uri: Option<String>,
    pub ctx_language: String,
    /// Full text of the active document (used for get_document_slice).
    pub ctx_full_text: Option<String>,
    /// Workspace root URIs.
    pub ctx_workspace_roots: Vec<String>,
    /// Cursor position in the active document.
    pub ctx_cursor_line: u32,
    pub ctx_cursor_col: u32,
    /// Selection range in the active document: (start_line, start_col, end_line, end_col).
    pub ctx_selection: Option<(u32, u32, u32, u32)>,
    /// Terminal IDs currently known to the editor.
    pub ctx_terminals: Vec<u32>,
    /// Set of panel IDs that are currently visible.
    pub ctx_visible_panels: std::collections::HashSet<String>,
    // ── Output accumulator ────────────────────────────────────────────────────
    /// Outputs queued during WASM calls; drained by `NativeExtension::poll`.
    pub pending: Vec<ExtensionOutput>,
    /// Extension id used to tag status bar / diagnostic outputs.
    pub ext_id: String,
}

impl HostState {
    fn new(ext_id: String) -> Self {
        Self {
            ctx_text: None,
            ctx_uri: None,
            ctx_language: String::new(),
            ctx_full_text: None,
            ctx_workspace_roots: Vec::new(),
            ctx_cursor_line: 0,
            ctx_cursor_col: 0,
            ctx_selection: None,
            ctx_terminals: Vec::new(),
            ctx_visible_panels: std::collections::HashSet::new(),
            pending: Vec::new(),
            ext_id,
        }
    }
}

// ── Host interface implementations ────────────────────────────────────────────

// The `types` interface defines only shared record/enum types — no functions.
// wasmtime bindgen still requires a `Host` impl for it.
impl crabide::extension::types::Host for HostState {}

impl crabide::extension::editor::Host for HostState {
    fn get_active_document_text(&mut self) -> Option<String> {
        self.ctx_text.clone()
    }
    fn get_active_document_uri(&mut self) -> Option<String> {
        self.ctx_uri.clone()
    }
    fn get_active_document_language_id(&mut self) -> Option<String> {
        Some(self.ctx_language.clone())
    }
    fn get_document_slice(&mut self, uri: String, r: wit::Range) -> Option<String> {
        // If the requested URI matches the active document, extract from the cached text.
        if self.ctx_uri.as_deref() == Some(&uri) {
            self.ctx_full_text.as_ref().and_then(|text| {
                let lines: Vec<&str> = text.lines().collect();
                let start_line = r.start.line as usize;
                let end_line = r.end.line as usize;
                if start_line >= lines.len() {
                    return None;
                }
                let end_line = end_line.min(lines.len().saturating_sub(1));
                let start_col = r.start.character as usize;
                let end_col = r.end.character as usize;
                if start_line == end_line {
                    let line = lines[start_line];
                    let start_col = start_col.min(line.len());
                    let end_col = end_col.min(line.len());
                    Some(line[start_col..end_col].to_owned())
                } else {
                    let mut result = String::new();
                    // First line from start_col
                    let first = lines[start_line];
                    let start_col = start_col.min(first.len());
                    result.push_str(&first[start_col..]);
                    result.push('\n');
                    // Middle lines
                    for line in &lines[start_line + 1..end_line] {
                        result.push_str(line);
                        result.push('\n');
                    }
                    // Last line up to end_col
                    let last = lines[end_line];
                    let end_col = end_col.min(last.len());
                    result.push_str(&last[..end_col]);
                    Some(result)
                }
            })
        } else {
            // For other documents, attempt to read from disk.
            let path = uri.strip_prefix("file://").unwrap_or(&uri);
            std::fs::read_to_string(path).ok()
        }
    }
    fn apply_edits(&mut self, uri: String, edits: Vec<wit::TextEdit>) -> Result<(), String> {
        let our_edits = edits
            .into_iter()
            .map(|e| {
                let wit_range = e.range;
                TextEdit {
                    range: (
                        wit_range.start.line,
                        wit_range.start.character,
                        wit_range.end.line,
                        wit_range.end.character,
                    ),
                    new_text: e.new_text,
                }
            })
            .collect();
        self.pending.push(ExtensionOutput::ApplyEdits {
            uri,
            edits: our_edits,
        });
        Ok(())
    }
    fn insert_at_cursor(&mut self, text: String) -> Result<(), String> {
        self.pending.push(ExtensionOutput::InsertAtCursor { text });
        Ok(())
    }
    fn get_cursor_position(&mut self) -> Option<wit::Position> {
        Some(wit::Position {
            line: self.ctx_cursor_line,
            character: self.ctx_cursor_col,
        })
    }
    fn set_cursor_position(&mut self, pos: wit::Position) -> Result<(), String> {
        self.pending.push(ExtensionOutput::SetCursorPosition {
            line: pos.line,
            character: pos.character,
        });
        Ok(())
    }
    fn get_selection_text(&mut self) -> String {
        match self.ctx_selection {
            Some((sl, sc, el, ec)) => self.ctx_full_text.as_ref().map_or(String::new(), |text| {
                let lines: Vec<&str> = text.lines().collect();
                let start_line = sl as usize;
                let end_line = el as usize;
                if start_line >= lines.len() {
                    return String::new();
                }
                let end_line = end_line.min(lines.len().saturating_sub(1));
                let start_col = sc as usize;
                let end_col = ec as usize;
                if start_line == end_line {
                    let line = lines[start_line];
                    let start_col = start_col.min(line.len());
                    let end_col = end_col.min(line.len());
                    line[start_col..end_col].to_owned()
                } else {
                    let mut result = String::new();
                    let first = lines[start_line];
                    let start_col = start_col.min(first.len());
                    result.push_str(&first[start_col..]);
                    result.push('\n');
                    for line in &lines[start_line + 1..end_line] {
                        result.push_str(line);
                        result.push('\n');
                    }
                    let last = lines[end_line];
                    let end_col = end_col.min(last.len());
                    result.push_str(&last[..end_col]);
                    result
                }
            }),
            None => String::new(),
        }
    }
    fn get_line_count(&mut self) -> Option<u32> {
        self.ctx_text.as_ref().map(|t| t.lines().count() as u32)
    }
}

impl crabide::extension::workspace::Host for HostState {
    fn get_workspace_roots(&mut self) -> Vec<String> {
        self.ctx_workspace_roots.clone()
    }
    fn read_file(&mut self, uri: String) -> Result<Vec<u8>, String> {
        let path = uri.strip_prefix("file://").unwrap_or(&uri);
        std::fs::read(path).map_err(|e| e.to_string())
    }
    fn write_file(&mut self, uri: String, content: Vec<u8>) -> Result<(), String> {
        let path = uri.strip_prefix("file://").unwrap_or(&uri);
        let text = String::from_utf8_lossy(&content).into_owned();
        self.pending.push(ExtensionOutput::WriteFile {
            path: PathBuf::from(path),
            content: text,
        });
        Ok(())
    }
    fn file_exists(&mut self, uri: String) -> bool {
        let path = uri.strip_prefix("file://").unwrap_or(&uri);
        std::path::Path::new(path).exists()
    }
    fn list_dir(&mut self, uri: String) -> Result<Vec<String>, String> {
        let path = uri.strip_prefix("file://").unwrap_or(&uri);
        let result: Vec<String> = std::fs::read_dir(path)
            .map_err(|e| e.to_string())?
            .filter_map(|e| e.ok())
            .filter_map(|e| e.path().to_str().map(|s| format!("file://{s}")))
            .collect();
        Ok(result)
    }
    fn find_files(&mut self, pattern: String) -> Vec<String> {
        // Simple glob walk of workspace roots.
        let mut results = Vec::new();
        for root in &self.ctx_workspace_roots {
            let path = root.strip_prefix("file://").unwrap_or(root);
            if let Ok(entries) = walk_files_recursive(std::path::Path::new(path), &pattern) {
                results.extend(entries);
            }
        }
        results
    }
}

/// Simple recursive file walk matching a filename glob pattern.
fn walk_files_recursive(dir: &std::path::Path, pattern: &str) -> Result<Vec<String>, String> {
    let mut results = Vec::new();
    if !dir.is_dir() {
        return Ok(results);
    }
    let entries = std::fs::read_dir(dir).map_err(|e| e.to_string())?;
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            results.extend(walk_files_recursive(&path, pattern)?);
        } else if let Some(name) = path.file_name().and_then(|s| s.to_str()) {
            if simple_glob_match(name, pattern) {
                let uri = format!(
                    "file:///{}",
                    path.to_string_lossy()
                        .replace('\\', "/")
                        .trim_start_matches('/')
                );
                results.push(uri);
            }
        }
    }
    Ok(results)
}

/// Minimal glob match supporting `*` (any chars) and `?` (single char).
fn simple_glob_match(name: &str, pattern: &str) -> bool {
    let name_chars: Vec<char> = name.chars().collect();
    let pat_chars: Vec<char> = pattern.chars().collect();
    let mut ni = 0;
    let mut pi = 0;
    let mut star_match = false;
    let mut star_pos = 0;
    let mut match_pos = 0;

    while ni < name_chars.len() {
        if pi < pat_chars.len() && (pat_chars[pi] == '?' || pat_chars[pi] == name_chars[ni]) {
            ni += 1;
            pi += 1;
        } else if pi < pat_chars.len() && pat_chars[pi] == '*' {
            star_match = true;
            star_pos = pi;
            match_pos = ni;
            pi += 1;
        } else if star_match {
            pi = star_pos + 1;
            match_pos += 1;
            ni = match_pos;
        } else {
            return false;
        }
    }
    while pi < pat_chars.len() && pat_chars[pi] == '*' {
        pi += 1;
    }
    pi == pat_chars.len()
}

impl crabide::extension::commands::Host for HostState {
    fn execute_command(&mut self, name: String, args: Vec<String>) -> Result<String, String> {
        // Queue a command execution request and return a placeholder result.
        // The app should handle ExtensionOutput::ExecuteCommand to actually run it.
        log::info!(
            "[wasm:{}] execute_command: {}({:?})",
            self.ext_id,
            name,
            args
        );
        Err("execute_command: not yet implemented in app".into())
    }
    fn show_quick_pick(&mut self, title: String, items: Vec<String>) -> Option<u32> {
        // Quick pick cannot return synchronously — queue a request and return None.
        self.pending.push(ExtensionOutput::Notification {
            message: format!("Quick pick requested: {title} ({} items)", items.len()),
            is_error: false,
        });
        log::info!(
            "[wasm:{}] show_quick_pick: {title} ({} items)",
            self.ext_id,
            items.len()
        );
        None
    }
    fn show_information(&mut self, message: String) {
        self.pending.push(ExtensionOutput::Notification {
            message,
            is_error: false,
        });
    }
    fn show_error(&mut self, message: String) {
        self.pending.push(ExtensionOutput::Notification {
            message,
            is_error: true,
        });
    }
    fn show_input_box(&mut self, prompt: String, _placeholder: Option<String>) -> Option<String> {
        // Input box cannot return synchronously — queue a notification and return None.
        self.pending.push(ExtensionOutput::Notification {
            message: format!("Input box requested: {prompt}"),
            is_error: false,
        });
        log::info!("[wasm:{}] show_input_box: {prompt}", self.ext_id);
        None
    }
}

impl crabide::extension::diagnostics::Host for HostState {
    fn publish(&mut self, uri: String, diags: Vec<wit::Diagnostic>) {
        let items = diags
            .into_iter()
            .map(|d| ExtensionDiagnostic {
                start_line: d.range.start.line,
                start_col: d.range.start.character,
                end_line: d.range.end.line,
                end_col: d.range.end.character,
                severity: wit_sev_to_ext(d.severity),
                message: d.message,
                source: d.source.unwrap_or_default(),
            })
            .collect();
        self.pending.push(ExtensionOutput::Diagnostics {
            extension_id: self.ext_id.clone(),
            uri,
            items,
        });
    }
    fn clear(&mut self, uri: String) {
        self.pending.push(ExtensionOutput::Diagnostics {
            extension_id: self.ext_id.clone(),
            uri,
            items: vec![],
        });
    }
    fn clear_all(&mut self) {}
}

impl crabide::extension::status_bar::Host for HostState {
    fn set_text(&mut self, text: String) {
        self.pending.push(ExtensionOutput::StatusBarText {
            extension_id: self.ext_id.clone(),
            text,
            tooltip: None,
            command: None,
            alignment: crate::host::StatusBarAlignment::Left,
        });
    }
    fn set_tooltip(&mut self, tooltip: String) {
        if let Some(ExtensionOutput::StatusBarText { tooltip: t, .. }) = self
            .pending
            .iter_mut()
            .rev()
            .find(|o| matches!(o, ExtensionOutput::StatusBarText { .. }))
        {
            *t = Some(tooltip);
        }
    }
    fn set_visible(&mut self, visible: bool) {
        self.pending.push(ExtensionOutput::StatusBarVisible {
            extension_id: self.ext_id.clone(),
            visible,
        });
    }
}

impl crabide::extension::terminal::Host for HostState {
    fn send_to_terminal(&mut self, terminal_id: u32, data: Vec<u8>) {
        self.pending
            .push(ExtensionOutput::SendToTerminal { terminal_id, data });
    }
    fn open_terminal(&mut self, title: String, command: Option<String>) -> u32 {
        self.pending
            .push(ExtensionOutput::OpenTerminal { title, command });
        0
    }
    fn list_terminals(&mut self) -> Vec<u32> {
        self.ctx_terminals.clone()
    }
}

impl crabide::extension::gutter::Host for HostState {
    fn set_markers(&mut self, uri: String, markers: Vec<wit::GutterMarker>) {
        let markers = markers
            .into_iter()
            .map(|m| GutterMarker {
                line: m.line,
                icon: m.icon,
                tooltip: m.tooltip,
                severity: m.severity.map(wit_sev_to_ext),
                command: m.command,
            })
            .collect();
        self.pending.push(ExtensionOutput::GutterMarkers {
            extension_id: self.ext_id.clone(),
            uri,
            markers,
        });
    }
    fn clear_markers(&mut self, uri: String) {
        self.pending.push(ExtensionOutput::GutterMarkers {
            extension_id: self.ext_id.clone(),
            uri,
            markers: vec![],
        });
    }
}

impl crabide::extension::panels::Host for HostState {
    fn show_panel(&mut self, panel_id: String) {
        self.pending.push(ExtensionOutput::ShowPanel { panel_id });
    }
    fn hide_panel(&mut self, panel_id: String) {
        self.pending.push(ExtensionOutput::HidePanel { panel_id });
    }
    fn is_panel_visible(&mut self, panel_id: String) -> bool {
        self.ctx_visible_panels.contains(&panel_id)
    }
}

// ── Helpers ───────────────────────────────────────────────────────────────────

fn wit_sev_to_ext(s: wit::DiagnosticSeverity) -> ExtensionSeverity {
    match s {
        wit::DiagnosticSeverity::Error => ExtensionSeverity::Error,
        wit::DiagnosticSeverity::Warning => ExtensionSeverity::Warning,
        wit::DiagnosticSeverity::Information => ExtensionSeverity::Information,
        wit::DiagnosticSeverity::Hint => ExtensionSeverity::Hint,
    }
}

fn wit_completion_kind(k: wit::CompletionKind) -> CompletionKind {
    match k {
        wit::CompletionKind::Text => CompletionKind::Text,
        wit::CompletionKind::Method => CompletionKind::Method,
        wit::CompletionKind::Function => CompletionKind::Function,
        wit::CompletionKind::Ctor => CompletionKind::Ctor,
        wit::CompletionKind::Field => CompletionKind::Field,
        wit::CompletionKind::Variable => CompletionKind::Variable,
        wit::CompletionKind::Class => CompletionKind::Class,
        wit::CompletionKind::Iface => CompletionKind::Iface,
        wit::CompletionKind::Module => CompletionKind::Module,
        wit::CompletionKind::Property => CompletionKind::Property,
        wit::CompletionKind::Keyword => CompletionKind::Keyword,
        wit::CompletionKind::Snippet => CompletionKind::Snippet,
        wit::CompletionKind::Color => CompletionKind::Color,
        wit::CompletionKind::File => CompletionKind::File,
        wit::CompletionKind::Reference => CompletionKind::Reference,
        wit::CompletionKind::Folder => CompletionKind::Folder,
        wit::CompletionKind::Constant => CompletionKind::Constant,
        wit::CompletionKind::Struct => CompletionKind::Struct,
        wit::CompletionKind::Operator => CompletionKind::Operator,
        wit::CompletionKind::TypeParameter => CompletionKind::TypeParameter,
    }
}

// ── WasmExtension ─────────────────────────────────────────────────────────────

/// A WASM extension loaded from a `.wasm` component binary.
///
/// Implements [`NativeExtension`] by forwarding all calls over the WIT boundary.
pub struct WasmExtension {
    store: Store<HostState>,
    bindings: CrabideExtension,
    manifest: ExtensionManifest,
}

impl WasmExtension {
    /// Load and compile a `.wasm` component, returning a boxed [`NativeExtension`].
    ///
    /// Reads the file, compiles it with the shared engine, sets up host functions,
    /// instantiates the component, and calls `get-manifest`.
    pub fn load(path: &PathBuf) -> Result<Box<dyn NativeExtension>, String> {
        let eng = engine();
        let bytes = std::fs::read(path).map_err(|e| format!("read {}: {e}", path.display()))?;
        let component =
            Component::new(eng, &bytes).map_err(|e| format!("compile {}: {e}", path.display()))?;

        let stem = path
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or("unknown")
            .to_owned();

        let mut linker: Linker<HostState> = Linker::new(eng);
        // wasmtime 34 bindgen! generates add_to_linker with HasSelf type parameter.
        CrabideExtension::add_to_linker::<_, HasSelf<_>>(&mut linker, |s| s)
            .map_err(|e| format!("add_to_linker: {e}"))?;

        let state = HostState::new(stem.clone());
        let mut store = Store::new(eng, state);

        let bindings = CrabideExtension::instantiate(&mut store, &component, &linker)
            .map_err(|e| format!("instantiate {}: {e}", path.display()))?;

        // Read manifest from the extension.
        let wit_manifest = bindings
            .crabide_extension_extension()
            .call_get_manifest(&mut store)
            .map_err(|e| format!("get-manifest trap in {}: {e}", stem))?;

        let id = wit_manifest.id.clone();
        store.data_mut().ext_id = id.clone();

        let manifest = ExtensionManifest {
            id,
            name: wit_manifest.name,
            description: wit_manifest.description,
            version: wit_manifest.version,
            author: wit_manifest.author,
            categories: vec![ExtensionCategory::Other],
            is_builtin: false,
        };

        Ok(Box::new(WasmExtension {
            store,
            bindings,
            manifest,
        }))
    }

    fn set_ctx(&mut self, ctx: &ExtensionContext) {
        let d = self.store.data_mut();
        d.ctx_text = ctx.active_text.map(str::to_owned);
        d.ctx_uri = ctx.active_uri.map(str::to_owned);
        d.ctx_language = ctx.active_language.to_owned();
        d.ctx_full_text = ctx.active_text.map(str::to_owned);
        d.ctx_workspace_roots = ctx
            .workspace_roots
            .iter()
            .map(|p| {
                let s = p.to_string_lossy();
                if s.starts_with('/') || s.contains(":\\") {
                    format!("file://{}", s.replace('\\', "/"))
                } else {
                    format!("file:///{}", s.replace('\\', "/"))
                }
            })
            .collect();
        d.ctx_cursor_line = ctx.cursor_line;
        d.ctx_cursor_col = ctx.cursor_col;
        d.ctx_selection = ctx.selection;
    }

    fn drain_pending(&mut self) -> Vec<ExtensionOutput> {
        std::mem::take(&mut self.store.data_mut().pending)
    }
}

impl NativeExtension for WasmExtension {
    fn manifest(&self) -> &ExtensionManifest {
        &self.manifest
    }

    fn activate(&mut self, ctx: &ExtensionContext) {
        self.set_ctx(ctx);
        if let Err(e) = self
            .bindings
            .crabide_extension_extension()
            .call_activate(&mut self.store)
        {
            log::error!("[wasm:{}] activate trap: {e}", self.manifest.id);
        }
    }

    fn deactivate(&mut self) {
        if let Err(e) = self
            .bindings
            .crabide_extension_extension()
            .call_deactivate(&mut self.store)
        {
            log::error!("[wasm:{}] deactivate trap: {e}", self.manifest.id);
        }
    }

    fn on_document_open(&mut self, uri: &str, language_id: &str, ctx: &ExtensionContext) {
        self.set_ctx(ctx);
        let uri_s = uri.to_string();
        let lang_s = language_id.to_string();
        if let Err(e) = self
            .bindings
            .crabide_extension_document_events()
            .call_on_document_open(&mut self.store, &uri_s, &lang_s)
        {
            log::error!("[wasm:{}] on_document_open trap: {e}", self.manifest.id);
        }
    }

    fn on_document_change(&mut self, uri: &str, ctx: &ExtensionContext) {
        self.set_ctx(ctx);
        let uri_s = uri.to_string();
        if let Err(e) = self
            .bindings
            .crabide_extension_document_events()
            .call_on_document_change(&mut self.store, &uri_s)
        {
            log::error!("[wasm:{}] on_document_change trap: {e}", self.manifest.id);
        }
    }

    fn on_document_save(&mut self, uri: &str, ctx: &ExtensionContext) {
        self.set_ctx(ctx);
        let uri_s = uri.to_string();
        if let Err(e) = self
            .bindings
            .crabide_extension_document_events()
            .call_on_document_save(&mut self.store, &uri_s)
        {
            log::error!("[wasm:{}] on_document_save trap: {e}", self.manifest.id);
        }
    }

    fn on_document_close(&mut self, uri: &str, ctx: &ExtensionContext) {
        self.set_ctx(ctx);
        let uri_s = uri.to_string();
        if let Err(e) = self
            .bindings
            .crabide_extension_document_events()
            .call_on_document_close(&mut self.store, &uri_s)
        {
            log::error!("[wasm:{}] on_document_close trap: {e}", self.manifest.id);
        }
    }

    fn on_cursor_move(&mut self, uri: &str, line: u32, col: u32, ctx: &ExtensionContext) {
        self.set_ctx(ctx);
        let uri_s = uri.to_string();
        let pos = wit::Position {
            line,
            character: col,
        };
        if let Err(e) = self
            .bindings
            .crabide_extension_cursor_events()
            .call_on_cursor_move(&mut self.store, &uri_s, pos)
        {
            log::error!("[wasm:{}] on_cursor_move trap: {e}", self.manifest.id);
        }
    }

    fn on_selection_change(
        &mut self,
        uri: &str,
        sl: u32,
        sc: u32,
        el: u32,
        ec: u32,
        ctx: &ExtensionContext,
    ) {
        self.set_ctx(ctx);
        let uri_s = uri.to_string();
        let sel = wit::Range {
            start: wit::Position {
                line: sl,
                character: sc,
            },
            end: wit::Position {
                line: el,
                character: ec,
            },
        };
        if let Err(e) = self
            .bindings
            .crabide_extension_cursor_events()
            .call_on_selection_change(&mut self.store, &uri_s, sel)
        {
            log::error!("[wasm:{}] on_selection_change trap: {e}", self.manifest.id);
        }
    }

    fn execute_command(&mut self, command: &str, args: &[String]) -> CommandResult {
        let cmd_s = command.to_string();
        let args_vec: Vec<String> = args.to_vec();
        match self
            .bindings
            .crabide_extension_command_handler()
            .call_execute(&mut self.store, &cmd_s, &args_vec)
        {
            Ok(wit::CommandResult::Ok) => CommandResult::Ok,
            Ok(wit::CommandResult::Error(e)) => CommandResult::Error(e),
            Err(e) => {
                log::error!("[wasm:{}] execute trap: {e}", self.manifest.id);
                CommandResult::Error(format!("trap: {e}"))
            }
        }
    }

    fn provide_gutter_markers(&mut self, uri: &str, ctx: &ExtensionContext) -> Vec<GutterMarker> {
        self.set_ctx(ctx);
        let uri_s = uri.to_string();
        match self
            .bindings
            .crabide_extension_gutter_provider()
            .call_provide_markers(&mut self.store, &uri_s)
        {
            Ok(markers) => markers
                .into_iter()
                .map(|m| GutterMarker {
                    line: m.line,
                    icon: m.icon,
                    tooltip: m.tooltip,
                    severity: m.severity.map(wit_sev_to_ext),
                    command: m.command,
                })
                .collect(),
            Err(e) => {
                log::error!("[wasm:{}] provide_markers trap: {e}", self.manifest.id);
                vec![]
            }
        }
    }

    fn provide_hover(
        &mut self,
        uri: &str,
        line: u32,
        col: u32,
        ctx: &ExtensionContext,
    ) -> Option<HoverResult> {
        self.set_ctx(ctx);
        let uri_s = uri.to_string();
        let pos = wit::Position {
            line,
            character: col,
        };
        match self
            .bindings
            .crabide_extension_hover_provider()
            .call_provide_hover(&mut self.store, &uri_s, pos)
        {
            Ok(Some(r)) => Some(HoverResult {
                start_line: r.range.start.line,
                start_col: r.range.start.character,
                end_line: r.range.end.line,
                end_col: r.range.end.character,
                contents: r.contents,
            }),
            Ok(None) => None,
            Err(e) => {
                log::error!("[wasm:{}] provide_hover trap: {e}", self.manifest.id);
                None
            }
        }
    }

    fn provide_completions(
        &mut self,
        uri: &str,
        line: u32,
        col: u32,
        ctx: &ExtensionContext,
    ) -> Vec<CompletionItem> {
        self.set_ctx(ctx);
        let uri_s = uri.to_string();
        let pos = wit::Position {
            line,
            character: col,
        };
        match self
            .bindings
            .crabide_extension_completion_provider()
            .call_provide_completions(&mut self.store, &uri_s, pos)
        {
            Ok(items) => items
                .into_iter()
                .map(|i| CompletionItem {
                    label: i.label,
                    detail: i.detail,
                    insert_text: i.insert_text,
                    kind: wit_completion_kind(i.kind),
                })
                .collect(),
            Err(e) => {
                log::error!("[wasm:{}] provide_completions trap: {e}", self.manifest.id);
                vec![]
            }
        }
    }

    fn on_terminal_output(&mut self, terminal_id: u32, data: &[u8]) -> Vec<ExtensionOutput> {
        if let Err(e) = self
            .bindings
            .crabide_extension_terminal_listener()
            .call_on_terminal_output(&mut self.store, terminal_id, data)
        {
            log::error!("[wasm:{}] on_terminal_output trap: {e}", self.manifest.id);
        }
        self.drain_pending()
    }

    fn poll(&mut self, _ctx: &ExtensionContext) -> Vec<ExtensionOutput> {
        self.drain_pending()
    }
}
