[profile.default]
# Show slowest tests at end.
slow-timeout = { period = "60s" }
failure-output = "immediate-final"
test-threads = "num-cpus"

# Retry flaky tests once.
retries = { backoff = "fixed", count = 1, delay = "1s" }

[profile.ci]
# CI profile: junit output.
failure-output = "immediate"
test-threads = "num-cpus"
junit = { path = "target/nextest/junit.xml" }
